# Generated by Django 5.2.17 on 2026-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_trabajador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='rostros_trabajadores/'),
        ),
    ]
