# Generated by Django 5.2.17 on 2026-09-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_trabajador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
